name: Create Repository
on:
  schedule:
    - cron:  '*/10 * * * *'
  push:
    branches: [ main ]
env:
  GIT_AUTHOR_NAME: mollybeach
  GIT_AUTHOR_EMAIL: mollyjbeach@gmail.com
jobs:
  create_repository:
    runs-on: ubuntu-latest
    steps:
      - name: Create new repository
        run: |
          # Set your GitHub username and repository name
          USERNAME=mollybeach
          REPO_NAME=beep
          
          # Create a new repository using the GitHub API
          curl -H "Authorization: token ${{ secrets.APP_GEN_TOKEN }}" --request POST --data '{"name":"'$REPO_NAME'"}' "https://api.github.com/user/repos"
