name: Create new repository
on:
  push:
    branches:
      - main
jobs:
  create-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Create Repository
        uses: f1lander/create-repository-action
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: meep
          description: A new repository
          private: false
          has_issues: true
          has_projects: true
          has_wiki: true
