name: Create new repository
on:
  push:
    branches:
      - main
jobs:
  create-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Create Repository
        uses: f1lander/create-repository-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: meep
          description: A new repository
          private: false
